spring:
  application:
    name:spring-flyway-tutorial
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
  
  # # http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
      
  flyway:
    enabled: true
    # When set to `true`, tells Flyway to perform baseline migration if no previous migrations have been applied to the database.
    # A baseline migration sets the baseline version for the database schema.
    baselineOnMigrate: true
    # When set to `true`, Flyway will validate the applied migrations against the available scripts to ensure they match.
    # If a mismatch is found, the application startup will fail.
    validateOnMigrate: true
    locations: classpath:db/migration